### ISSUE TITLE
set memory qualifiers in pgcraft

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [gopro/gopro-lib-node.gl#105]
Can we set memory qualifiers in inject_block (e.g. readonly, writeonly, etc)?

https://github.com/gopro/gopro-lib-node.gl/blob/4e1456401fe96fb12c058e30bcc0d1f398854ec9/libnodegl/pgcraft.c#L455

for data unit tests: if we don't set "readonly" for glsl buffer we get compile error:
Shader requires fragmentStoresAndAtomics but is not enabled on the device

**Comment by cboesch-gpsw** [comment]
Sure, can you send a patch? There is already something similar done for the images. So you could add a `writable` field to `pgcraft_block` (like it's done in `pgcraft_texture`), set it appropriately in `pass.c`, and then adjust `pgcraft.c` to add the qualifier (maybe only when it's supported? not exactly sure of the support).

**Comment by jmoguillansky-gpsw** [comment]
Here's more info:

some devices don't support writing to a buffer (SSBO) in vertex or fragment stage.  It's an optional feature.
See vkcontext.c: "vertexPipelineStoresAndAtomics" and "fragmentStoresAndAtomics".

In this case we have to specify "readonly" on the buffer in glsl.  

Here's the steps to reproduce the compile error.  

Step 1: in vkcontext.c: disable features "vertexPipelineStoresAndAtomics" and "fragmentStoresAndAtomics".  

Step 2: the following unit tests should reproduce: compute_particules, and various data unit tests.

The solution: we can put more precise memory qualifiers (e.g. mark buffer as readonly if we only read from it).

**Comment by jmoguillansky-gpsw** [comment]
Here's a patch, but not sure if it's the best solution:

in pgcraft.c, in inject_block:

    const char* memory_qualifiers = (stage == NGLI_PROGRAM_SHADER_COMP) ? "" : "readonly";
    ngli_bstr_printf(b, " %s %s %s_block {\n", keyword, memory_qualifiers, named_block->name);

**Comment by ubitux** [comment]
I explained in details what you can do to fix, it's not much changes. Please send a patch/make a PR.

**Comment by jmoguillansky-gpsw** [comment]
Sure I'll make a PR

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
