### ISSUE TITLE
Texture usage flags

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [gopro/gopro-lib-node.gl#106]
Can we provide more specific texture usage flags (e.g. color_attachment, depth_stencil_attachment, transfer_src, transfer_dst, sampled: similar to vulkan image usage flags)?

This will be very helpful for integrating the various backends.

https://github.com/gopro/gopro-lib-node.gl/blob/4e1456401fe96fb12c058e30bcc0d1f398854ec9/libnodegl/texture.h#L71

**Comment by mbouron-gpsw** [comment]
Added in 5b4ad504580995ec5979a6eadf96e8736105e3a2.
