### ISSUE TITLE
Implicit clears

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [gopro/gopro-lib-node.gl#108]
Instead of explicitly clearing attachments: can we specify the clear values and clear operation in renderpass?

https://github.com/gopro/gopro-lib-node.gl/blob/4e1456401fe96fb12c058e30bcc0d1f398854ec9/libnodegl/gctx.h#L60

**Comment by mbouron-gpsw** [comment]
Explicit clear functions have been removed since 3259577b13dc8ecc8d90174b133d0d1b8c5d0c3f.
