### ISSUE TITLE
Optimized Image Layouts

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [gopro/gopro-lib-node.gl#110]
Can we use more optimized image layout (e.g. SHADER_READ_ONLY_OPTIMAL)?  

https://github.com/gopro/gopro-lib-node.gl/blob/4e1456401fe96fb12c058e30bcc0d1f398854ec9/libnodegl/texture_vk.c#L426

**Comment by cboesch-gpsw** [comment]
Supported since Vulkan integration.
