### ISSUE TITLE
HUD: move code to the core

### ISSUE THREAD

**Issue by cboesch-gpsw** [gopro/gopro-lib-node.gl#18]
Multiple HUD node are not possible, so it doesn't make much sense to have it in a node instead of globally. If the HUD node is to be kept, it should only display/export the global information. That benchmarking code might have its place in the new backend infrastructure.

**Comment by mbouron-gpsw** [comment]
This has been addressed by 73a58a156560cd4fd3efdb15fde0352529a02e9c.
