### ISSUE TITLE
ngl-viewer should remember its last position, geometry and screen

### ISSUE THREAD

**Issue by jbnoel-gpsw** [gopro/gopro-lib-node.gl#3]

**Comment by cboesch-gpsw** [comment]
Config support was added in https://github.com/gopro/gopro-lib-node.gl/commit/08c9663e18c57baa1fc6af73bdf2806844057db3

The screen is not memorized, but this should be do-able by the window manager. (Technically, the geometry and positioning also falls in that category, but were simple enough to be added in the configuration).
