### ISSUE TITLE
show_fps overlay should have a fixed length for numbers

### ISSUE THREAD

**Issue by jbnoel-gpsw** [gopro/gopro-lib-node.gl#6]
It is hard to read the numbers because they are always moving because of the changing length of the string.

**Comment by cboesch-gpsw** [comment]
A few improvements in the FPS node fixed this:
- averaging window (reducing number differences)
- small refresh rate (8x/second)
- larger text

This node still needs improvements (such as displaying GPU timings and not only CPU), for now at least it's readable. It's probable the node will be renamed in the future (as "Bench" or "stats" for example)
