### ISSUE TITLE
ngl-viewer crashes when changing the name of the scene during playback

### ISSUE THREAD

**Issue by jbnoel-gpsw** [gopro/gopro-lib-node.gl#7]

**Comment by cboesch-gpsw** [comment]
After a discussion it appears to be due to `fractions` module reload causing issues. This is fixed in https://github.com/gopro/gopro-lib-node.gl/commit/602d0cecd52885094cc3f46f62f8def5ca9b6ec2

Another possible reason for the crash may have been nodes object instantiated in another thread.
